name: Prettier checks

# This action works with pull requests and pushes
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - name: Checks
              run: nix run nixpkgs#nodePackages.prettier -- --check .
