# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    push:
        branches:
            - main
    pull_request:

name: "Static analysis"

jobs:
    run:
        name: "Static Analysis"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ["8.1"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: Install PHP
              uses: shivammathur/setup-php@2.19.0
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: gd,mbstring,pcov,xdebug
                  tools: cs2pr

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Grumphp
              run: vendor/bin/grumphp run --tasks=psalm,phpstan -n

            - name: Send feedback on Github
              if: ${{ failure() }}
              run: |
                  vendor/bin/phpstan analyse -l max --error-format=checkstyle src/ | cs2pr
                  vendor/bin/psalm --output-format=github | cs2pr

            - name: Send PSALM data
              run: vendor/bin/psalm --shepherd --stats src/
              continue-on-error: true
