# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    push:
        branches:
            - main
    pull_request:

name: "Unit tests"

jobs:
    run:
        name: "Unit Tests"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]
                php-versions: ["8.1"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v2.4.0
              with:
                  fetch-depth: 2

            - name: Install PHP
              uses: shivammathur/setup-php@2.17.1
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: gd,mbstring,pcov,xdebug

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2.1.7
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Grumphp
              env:
                XDEBUG_MODE: coverage
              run: vendor/bin/grumphp run --tasks=phpunit,clover_coverage

            - name: Send Scrutinizer data
              run: |
                  composer require scrutinizer/ocular --dev
                  vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/coverage/clover.xml
              continue-on-error: true
